In [16]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

# Files to load
city_data_to_load = "Resources/city_data.csv"
ride_data_to_load = "Resources/ride_data.csv"

# Read the City and Ride Data
city_data_df = pd.read_csv(city_data_to_load)
ride_data_df = pd.read_csv(ride_data_to_load)



# Combine the data into a single dataset
pyber_data_df = pd.merge(ride_data_df, city_data_df, how="left", on=["city", "city"])

# Display the data table for preview
pyber_data_df



Pyber_type = pyber_data_df.groupby(["type"])
#  1. Get the total rides for each city type
Pyber_ride_count = pyber_data_df.groupby(["type"]).count()["ride_id"]
Pyber_ride_count


#  2. Get the total drivers for each city type
Pyber_driver_count = pyber_data_df.groupby(['type']).sum()['driver_count']
Pyber_driver_count

#  3. Get the total amount of fares for each city type
Pyber_fares = pyber_data_df.groupby(["type"]).sum()["fare"]
print(Pyber_fares)

#  4. Get the average fare per ride for each city type. 
Pyber_average_fare = pyber_data_df.groupby(["type"]).mean()["fare"]
Pyber_average_fare

#  5. Get the average fare per driver for each city type. 
Pyber_average_fare_per_driver = Pyber_fares / Pyber_driver_count
Pyber_average_fare_per_driver


#  6. Create a PyBer summary DataFrame. 
Pyber_Summary_df = pd.DataFrame([{"Type": Pyber_type, "Total Rides": Pyber_ride_count, "Total Drivers": Pyber_driver_count, "Total Fares": Pyber_fares, "Average Fares Per Driver": Pyber_average_fare_per_driver}])




#  7. Cleaning up the DataFrame. Delete the index name
Pyber_Summary_df.index.name = None

#  8. Format the columns.

# Reorder the columns in the order you want them to appear.
new_column_order = ["Type", "Total Rides", "Total Drivers", "Total Fares", "Average Fares Per Driver"]\


Pyber_Summary_df = Pyber_Summary_df[new_column_order]



Pyber_Summary_df`

type
Rural        4327.93
Suburban    19356.33
Urban       39854.38
Name: fare, dtype: float64

,Type,Total Rides,Total Drivers,Total Fares,Average Fares Per Driver
0,<pandas.core.groupby.generic.DataFrameGroupBy ...,type Rural 125 Suburban 625 Urban ...,type Rural 537 Suburban 8570 Urban...,type Rural 4327.93 Suburban 19356.33...,type Rural 8.059460 Suburban 2.258615...

In [34]:
# 1. Read the merged DataFrame

# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd


# Files to load
city_data_to_load = "Resources/city_data.csv"
ride_data_to_load = "Resources/ride_data.csv"

# Read the City and Ride Data
city_data_df = pd.read_csv(city_data_to_load)
ride_data_df = pd.read_csv(ride_data_to_load)



# Combine the data into a single dataset
pyber_data_df = pd.merge(ride_data_df, city_data_df, how="left", on=["city", "city"])

# Display the data table for preview
pyber_data_df




# 2. Using groupby() to create a new DataFrame showing the sum of the fares 
#  for each date where the indices are the city type and date

d2_df = pd.DataFrame(pyber_data_df.groupby(["type","date"]).sum()["fare"])
d2_df

# 3. Reset the index on the DataFrame you created in #1. This is needed to use the 'pivot()' function.
df = d2_df.reset_index()


# 4. Create a pivot table with the 'date' as the index, the columns ='type', and values='fare' 
# to get the total fares for each type of city by the date. 
pivot(df)


# 5. Create a new DataFrame from the pivot table DataFrame using loc on the given dates, '2019-01-01':'2019-04-29'.

NameError: name 'pivot' is not defined